language: python
python:
  - 3.6
  - 3.7-dev
before_install:
  - pip install pipenv
install:
  - pipenv install
  - pip install -e .
  - pip install codecov
script:
  - pytest --flake8 --cov
after_success:
  - codecov
notifications:
  email: never
